INSERT INTO `estados` (`idEstado`,`NombreEstado`,`DescripcionEstado`) VALUES
(1, 'Soltero(a)',''),
(2, 'Casado(a)',''),
(3, 'Divorciado(a)',''),
(4, 'Conviviente',''),
(5, 'Separado(a)',''),
(6, 'Viudo(a)',''),
(7, 'Prioridad Alta',''),
(8, 'Prioridad Moderada',''),
(9, 'Prioridad Baja',''),
(10, 'En Espera',''),
(11, 'Pendiente',''),
(12, 'En Proceso',''),
(13, 'En Espera',''),
(14, 'Finalizado',''),
(15, 'Atrazado',''),
(16, 'Activo',''),
(17, 'Transitivo',''),
(18, 'Inactivo',''),
(19, 'Confirmado',''),
(20, 'Sin Confirmar',''),
(21, 'Cancelado',''),
(22, 'Habilitado',''),
(23, 'Suspendido',''),
(24, 'Dado de baja',''),
(25, 'Verificado',''),
(26, 'Actualizado',''),
(27, 'Aprobado',''),
(28, 'Desaprobado',''),
(29, 'Operativo',''),
(30, 'En reparación',''),
(31, 'No Operativo',''),
(32, 'Programado',''),
(33, 'Reprogramado',''),
(34, 'Prioridad Alta',''),
(35, 'Prioridad Baja',''),
(36, 'Urgente',''),
(37, 'Muy Urgente',''),
(38, 'Enviado',''),
(39, 'Recibido',''),
(40, 'Optimo',''),
(41, 'Defectuoso',''),
(42, 'Incompleto',''),
(43, 'Completo',''),
(44, 'Manchado',''),
(45, 'Quemado',''),
(46, 'Otro Problemaa',''),
(47, 'Ningun Problema','');
