


INSERT INTO `personas` (`idPersona`,`idTipoIdentificacion`,`NumIdentificacion`,`NombrePersona`,`ApellidoPaterno`,`ApellidoMaterno`,`IdSexo`,`IdDireccion`,`FechaNacimiento`,`FechaRegistra`) VALUES
(1,1,'','MARCO ANTONIO','ARBIETO','MALLMA',1,'','',''),
(2,1,'','EFRAIN','CHAVEZ','ARAINDIA',1,'','',''),
(3,1,'','CONSUELO FLORIANA','ESPINOZA','CARUZ',2,'','',''),
(4,1,'','FLOR DE DIAMELA','CAYAO','QUINTANA',2,'','',''),
(5,1,'','JACQUELIN','LUCANO','JUAREZ',2,'','',''),
(6,1,'','JULIHNO JEFERHSON','MENDOZA','VERAMENDI',1,'','',''),
(7,1,'','KAREN LESLIE','LUIS','MORALES',2,'','',''),
(8,1,'','LILIANA JANETH','RAMOS','LUIS',2,'','',''),
(9,5,'','MANUEL','VOLCANES','BANGEL',1,'','',''),
(10,1,'','MARLENE ADELINA','MENDOZA','AVILA',2,'','',''),
(11,1,'','OLGA','CHEPE','CULANTRES',2,'','',''),
(12,1,'','SAMIRA MICSI','LEDEZMA','MIRANDA',2,'','',''),
(13,1,'','PATRICIA ANA','TORRES','VENEGAS',2,'','',''),
(14,1,'','GIAN FRANCO SIMONE','YUMBATO','APOLINARIO',1,'','','');


INSERT INTO `personas` (`idPersona`, `idTipoIdentificacion`, `NumIdentificacion`, `NombrePersona`, `ApellidoPaterno`, `ApellidoMaterno`, `IdSexo`, `IdDireccion`, `FechaNacimiento`, `FechaRegistra`) VALUES 
(NULL, NULL, NULL, 'LEONARDO', 'REZA', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JESUS', 'CASTAÑEDA', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'PIERO RAUL', 'MEDRANO', 'GARAY', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JAQUELINE', 'LINCHE', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'VALERI', 'VALENCIA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANTONI', NULL, NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ELVA', 'BEERRA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ISIS', 'AMERICA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'IRENE', 'MARWUEZ', 'MOSCOSO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LUIS', 'MEDRANO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARISOL', 'ROJAS', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LEONARDO', 'CABELLO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANTHONY', 'SAN MIGUEL', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ARTURO', 'ROMANI', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ADELMO', 'QUISPE', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LUIS', 'ANTONIO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'DANIEL', 'DAVILA', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALESANDRA', 'PADILLA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'SHEYLA', NULL, NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JOSE', 'MIGUEL', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LIZ', NULL, NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ROSSIND', 'MEZA', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JOSE', 'CARDO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RICARDO', NULL, NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'WILDER', 'SERNA', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JOHAN', 'PACHECO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARLOS', 'PACHAS', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'HENRY', NULL, NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'HUBER', 'CHINCHAY', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CACERES', 'MONZON', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GRACIEL', 'RAFAEL', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'NANCY', 'CARO', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JUAN FRANCISCO', 'RETUERTO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'EYLEN MINERVA DE LOS ANGELES', 'OBLITAS', 'GUERRERO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARLOS', ' HUAMALI', 'CAMAVILCA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA', 'ALEJANDRA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MIRANDA', 'RICHARD', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA', 'CARRASCO', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ROCIO CAROLYN', 'VERNAZZA', 'NIÑO DE GUZMAN', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA LUISA', 'TARANCO', 'PAREDES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'VICENTE PAUL', 'REAL', 'AYALA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANALY', 'MELGAR', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'KATHERINE', 'FIEROO', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RENZO MARTIN', 'MARQUINA', 'SILVA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JESUS MARIA', 'ECHE', 'RUIZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'DARIANNYS', 'MANZANILLA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEXANDER', 'MESONES', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JULIO CESAR', 'SUSANIBAR', 'ORTIZ', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MIGUEL', 'CAMUS', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JULIO', 'HUANASI', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'WILLIAMS LUIS', 'BARNUEVO', 'EDUARDO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEXANDRA DANIELA', 'BARNUEVO', 'JUAREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JESUS EMERSON', 'HUAMANI', 'HUAMANI', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'TATIANA LEONOR', 'SILVA', 'PEREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARINA', 'SILVA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA EVELYN', 'MORENO', 'LLANOS', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'OSMAR', 'PEREZ', 'PEREZ', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JUAN ANTONIO', 'RAMOS', 'YUPANQUI', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LUZ FIORELLA', 'ARCE', 'RAMIREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'NORMA MARINA', 'ROJAS', 'OSORIO DE SANCHEZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MILAGROS FLORENCIA', 'PAULINO', 'ARANDA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MAX ANDRE', 'YLIZARBE', 'MOSCOSO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MIGUEL ANGEL', 'CHAFLOQUE', 'PAZ', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JULIO CESAR', 'SUAREZ', 'CARBAJAL', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEXANDER', 'MESONES', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'PATRICIA PAOLA', 'PECHE', 'BECERRA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JHON HENRY', 'VARA', 'CAMPOS', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEJANDRO', 'PACHECO', 'MAURICIO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'DANNY HENRY', 'ATAUCUSI', 'SILVA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LEIDY ROSALYN', 'ORTIZ', 'RICALDI', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'NICOLAS', 'ALFARO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANGEL', 'ROJAS', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'FERNANDO', 'CONTRERAS', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JHON HENRY', 'VARA', 'CAMPOS', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RONALD ADRIAN', 'DIAZ', 'COLCA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIANO', 'MONCAYO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARMEN LOURDES', 'ALIAGA', 'TAMBINI VDA DE ROMERO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JIMENA', 'PUENTE DE LA VEGA HANCCO', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'NELLY MARITZA', 'CANCHES', 'GONZALES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JOSE MIGUEL', 'CUBA', 'RIVERO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RICARDO', 'CAMIZAN', 'SANGAMA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA', 'VILLACAMPO', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'SANDRA NATALIA', 'LLANOS', 'JAIME', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARY LUZ', 'OSCATEGUI', 'LARIOS', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ESTEFANO PAOLO', 'CAJO', 'MOREY', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARIA IRENE', 'MARQUEZ', 'MOSCOSO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANA', 'SIFUENTES', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JOSE RICARDO', 'SUSANIBAR', 'MORENO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'YEFRY CARLOS', 'PAREDES', 'VELASQUEZ', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'BRIGITH', NULL, NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'PAMELA', 'PERES', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MERY DELIA', 'CORONADO', 'HUAMAN', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ABNER ISAI', 'MARIANO', 'IBAÑEZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GLICERIA PETRONILA', 'FRANCIA', 'MACAZANA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'TANIA JUDITH', 'TELLO', 'CHUMPITAZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JORGE', 'GABRIEL', 'QUISPE', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARMEN ROSA MARIA', 'ARIAS', 'PAREDES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ROUSS', 'CALLE', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'DENNIS AMERICO', 'HERRERA', 'ENRIQUEZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARISOL', 'SALAZAR', 'ROMAN', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARLO VALENTINO', 'LIVIA', 'PAUCCA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'PABEL', 'GARCIA', 'GAMARRA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LUCIA ERACLEA', 'MADUEÑO', 'EVANGELISTA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JULIO', 'ZARATE', NULL, '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARLENE', 'QUISPE', 'ALARTE', '2', NULL, NULL, current_timestamp())
(NULL, NULL, NULL, 'YULIANA', 'MARQUEZ', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ZULEMA', 'SILVA', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANNIE JOSELINE', 'BAZAN', 'MALLMA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'EVA GRACIELA', 'CASSANO', 'BARBOZA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JUAN FRANCISCO', 'RETUERTO', 'ALBURQUEQUE', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARICRUZ', 'RIVERA', 'RAMIREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MERY', 'CARBAJAL', NULL, '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JULIO CESAR', 'SUAREZ', 'CARBAJAL', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARILYN ELIZABETH', 'PEÑA', 'CORONADO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ROSMERY NATALY', 'LEVANO', 'BALDEON', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'VIANNEY MARGARITA', 'HUAMANYAURI', 'CUELLAR', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEXIS GOHAN', 'VALDIVIA', 'ARELLANO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CLAUDIA INES', 'RIVEROS', 'MARTINEZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'WILDER CESAR', 'SERNA', 'SANTOS', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ENMANUEL ALONSO', 'MEZA', 'HORNA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'LORENA MARIA EMILIA', 'VARGAS', 'ALEGRIA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GISELLA', 'RICALDI', 'FERNANDEZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GRECIA KATHERINE', 'VARGAS', 'ALEGRIA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CARLA KATTERINE', 'MUNDO', 'LEVANO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JHERSON CARLOS', 'HUAREZ', 'SALAZAR', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MILUSKA', 'SEGURA', 'LEVANO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RONALD ALEXIS', 'CHAVEZ', 'MENDEZ', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GERARDO', 'PANDURO', 'CASTRO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JESUS GABRIELA', 'ROJAS', 'ROMERO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'HANNA', 'GARCIA', 'VILCHES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'DERMALY', 'FERNANDEZ', 'CONTRERAS', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'OSCAR ADRIAN', 'SALAZAR', 'CASTILLO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JENNIFER FIORELLA', 'ESPINOZA', 'CHINCHAY', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'VALERY JAVIER', 'MOSTACERO', 'SOSA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JHOAN ALEXANDER', 'HUARINGA', 'CHAGRAY', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'SHIRLEY SARA', 'ARIAS', 'CABRERA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ELENA NONA NATIVIDAD', 'CARDENAS', 'MOSCOSO', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JESICA', 'CHAGRAY', 'CUELLAR', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANA LUCIA', 'CACERES', 'REYES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'WILLIAM ARTURO', 'CALLUPE', 'LLAJA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GLADYS VANESSA DEL PILAR', 'MAMANI', 'ARRIOLA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARISOL', 'PAUCAR', 'FLORES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RICARDO ANDRE', 'RIVERA', 'CORNEJO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'GISEL NOEMI', 'VELIZ', 'FRANCIA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'REY DAVID', 'VENTOCILLA', 'TALAVERANO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ANDREA', 'CASTAÑEDA', 'MARCA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CLAUDIA MARIA', 'ANTONIO', 'PIMENTEL', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'HELEN YESENIA', 'ARANGO', 'PEREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'FLOR DE MARIA', 'AREVALO', 'TERRONES', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ROCIO', 'BACA', 'CABRAL', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'ALEXANDRA DANIELA', 'BARNUEVO', 'JUAREZ', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARITZA FIORELLA', 'BAZAN', 'MALLMA', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'PATRICIA CECILIA', 'BELTRAN', 'COLAN', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'JHEINER YURI', 'BLAS', 'ROJAS', '2', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'CAMIZAN', 'SANGAMA', 'RENATO', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'RICARDO', 'CAMIZAN', 'SANGAMA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MARCO ANTONI', 'CONDORI', 'CHIPANA', '1', NULL, NULL, current_timestamp()),
(NULL, NULL, NULL, 'MANUEL OCTAVIO', 'PALACIOS', 'SANCHEZ', '1', NULL, NULL, current_timestamp());


LEONARDO REZA	972752665	11-Ago	MANUEL VOLCANES
JESUS CASTAÑEDA	968484879	13-Jun	GABRIEL FLORES

PIERO RAUL MEDRANO GARAY	926480675	8-Abr	GERARDO RAMIREZ
JAQUELINE LINCHE 	942445235	25-Jul	GERARDO RAMIREZ
VALERI VALENCIA	965825217	12-Ene	FLOR CAYAO
ANTONI	994109338		JULIHNO MENDOZA 
ELVA BEERRA 	989353554		FLOR CAYAO
ISIS AMERICA	999981901	14-May	CONSUELO ESPINOSA
IRENE MARWUEZ MOSCOSO	986470471	19-Set	MARLENE MENDOZA
LUIS MEDRANO	993391491	14-Set	GERARDO RAMIREZ
LEONARDO CABELLO 	926835966	31-Jul	GABRIEL FLORES
MARISOL ROJAS	941131082	9-Oct	PATRICIA TORRES
ANTHONY SAN MIGUEL	975627441	6-Dic	GERARDO RAMIREZ
ARTURO ROMANI	966889421	16-Dic	GABRIEL FLORES
ADELMO QUISPE	954824263		JULIHNO MENDOZA 
LUIS ANTONIO	943908613		FLOR CAYAO
DANIEL DAVILA 	971168463		JULIHNO MENDOZA 
ALESANDRA PADILLA	965785348		JACQUELIN LUCANO
SHEYLA	997428970		CONSUELO ESPINOSA
JOSE MIGUEL	964188218		GERARDO RAMIREZ
LIZ	970656736		JULIHNO MENDOZA 
ROSSIND MEZA	999929710		GERARDO RAMIREZ
JOSE CARDO	990583151		MANUEL VOLCANES
RICARDO	973739429		JULIHNO MENDOZA 
WILDER SERNA	951689745		MANUEL VOLCANES
JOHAN PACHECO	971495766		GERARDO RAMIREZ
CARLOS PACHAS	940664113		GERARDO RAMIREZ
HENRY	954274012		OLGA CHEPE
HUBER CHINCHAY	990996210		GERARDO RAMIREZ
CACERES MONZON	982243261		JULIHNO MENDOZA 
GRACIEL RAFAEL 	970352329	10-Abr	PATRICIA TORRES
NANCY CARO	987423940	7-Dic	OLGA CHEPE
JUAN FRANCISCO RETUERTO		11-Jul	MANUEL VOLCANES
OBLITAS GUERRERO EYLEN MINERVA DE LOS ANGELES	907558406	24-Abr	JACQUELIN LUCANO
 HUAMALI CAMAVILCA CARLOS	946304316	15-Ago	MANUEL VOLCANES
MARIA ALEJANDRA	948505057	12-Jun	JACQUELIN LUCANO
RICHARD MIRANDA	970842566	19-Jul	OLGA CHEPE
MARIA CARRASCO	970718235	9-Jul	OLGA CHEPE
VERNAZZA NIÑO DE GUZMAN ROCIO CAROLYN	966928587	24-Nov	MARLENE MENDOZA
TARANCO PAREDES MARIA LUISA	992309876	18-Ene	OLGA CHEPE
REAL AYALA VICENTE PAUL	993171682	27-Jun	MANUEL VOLCANES
ANALY MELGAR	994998487	5-Feb	GERARDO RAMIREZ
KATHERINE FIEROO	949713257	6-Ene	PATRICIA TORRES
MARQUINA SILVA RENZO MARTIN	964865522	4-May	GERARDO RAMIREZ
ECHE RUIZ JESUS MARIA	993911611	29-Dic	MARLENE MENDOZA

DARIANNYS MANZANILLA	985739626	4-Mar	JACQUELIN LUCANO
ALEXANDER MESONES	968738016	17-Ene	GERARDO RAMIREZ
SUSANIBAR ORTIZ JULIO CESAR	973913862	21-Jul	GERARDO RAMIREZ
MIGUEL CAMUS	945446743	7-May	GERARDO RAMIREZ
JULIO HUANASI	981584830	11-Jun	MANUEL VOLCANES
RIVERA EDUARDO WILLIAMS LUIS	946372724	3-Abr	MANUEL VOLCANES
BARNUEVO JUAREZ ALEXANDRA DANIELA	982281106	21-Oct	FLOR CAYAO - MARLENE - CONSUELO
HUAMANI HUAMANI JESUS EMERSON	946233783	18-Feb	GABRIEL DEL PINO
SILVA PEREZ TATIANA LEONOR	947055268	10-Feb	MANUE/OLGA
MARINA SILVA	949000830	29-Nov	FLOR CAYAO
MORENO LLANOS MARIA EVELYN	964163238	26-Mar	MARLENE/OLGA
PEREZ PEREZ OSMAR	991365724	7-Nov	MANUEL VOLCANES
 RAMOS YUPANQUI JUAN ANTONIO	989097897	8-Mar	GERARDO RAMIREZ
ARCE RAMIREZ LUZ FIORELLA	961623841	2-May	JACQUELIN LUCANO
ROJAS OSORIO DE SANCHEZ NORMA MARINA	949100562	5-Jun	MARLENE/CONSUELO/FLOR/JACQUI
PAULINO ARANDA MILAGROS FLORENCIA	999229223	19-Oct	FLOR/GERARDO
YLIZARBE MOSCOSO MAX ANDRE	949965696	20-Ene	GABRIEL DEL PINO
CHAFLOQUE PAZ MIGUEL ANGEL	932314482	26-Jun	MANUEL VOLCANES
SUAREZ CARBAJAL JULIO CESAR	969173225	7-Feb	OLGA/JACQUELIN
PECHE BECERRA PATRICIA PAOLA	991829413	26-Ene	JACQUELIN LUCANO

VARA CAMPOS JHON HENRY	923443050	24-Ago	GERARDO/GABRIEL
PACHECO MAURICIO ALEJANDRO	999610420	23-Feb	GERARDO RAMIREZ
ATAUCUSI SILVA DANNY HENRY	989035832	19-Nov	MANUEL VOLCANES
ORTIZ RICALDI LEIDY ROSALYN	924558017	11-Jun	GABRIEL DEL PINO
NICOLAS ALFARO	902282162	15-May	GERARDO RAMIREZ
ANGEL ROJAS	970448215	14-Dic	MANUEL VOLCANES
FERNANDO CONTRERAS	924442604	17-Ene	GERARDO/MANUEL
VARA CAMPOS JHON HENRY	970750975	21-Oct	FLOR CAYAO
DIAZ COLCA RONALD ADRIAN	989714813	3-Abr	GABRIEL DEL PINO
MARIANO MONCAYO	902140149	17-Ene	MANUEL VOLCANES
ALIAGA TAMBINI VDA DE ROMERO CARMEN LOURDES	953853870	17-Abr	GABRIEL DEL PINO
PUENTE DE LA VEGA HANCCO JIMENA	977763393	17-Set	CONSUELO/JACQUELIN
CANCHES GONZALES NELLY MARITZA	990924265	2-Jun	OLGA/ JACQUELIN
CUBA RIVERO JOSE MIGUEL	993233726	10-May	FLOR CAYAO
CAMIZAN SANGAMA RICARDO	937337503	26-Ene	GABRIEL DEL PINO
MARIA VILLACAMPO	947034486	30-May	LILIANA RAMOS LUIS
LLANOS JAIME SANDRA NATALIA	982958581	21-Jun	OLGA/FLOR
OSCATEGUI LARIOS MARY LUZ	954700350	26-Abr	MARLENE/LILIANA
CAJO MOREY ESTEFANO PAOLO	906285800	3-Dic	GERARDO RAMIREZ
MARQUEZ MOSCOSO MARIA IRENE	986470471	19-Set	MARLENE
ANA SIFUENTES	989744183	21-Nov	FLOR CAYAO

SUSANIBAR MORENO JOSE RICARDO	987149575	21-Feb	MANUEL VOLCANES
PAREDES VELASQUEZ YEFRY CARLOS	972398718	17-Feb	PATRICIA TORRES
BRIGITH	916300144	7-Ene	OLGA CHEPE
PAMELA PERES	942750810	6-Feb	OLGA CHEPE
CORONADO HUAMAN MERY DELIA	997272616	18-May	OLGA CHEPE
MARIANO IBAÑEZ ABNER ISAI	960756302	23-Jul	GABRIEL DEL PINO
FRANCIA MACAZANA GLICERIA PETRONILA	99263443	21-Dic	MARLENE/JACQUELIN
TELLO CHUMPITAZ TANIA JUDITH	933894690	18-Jul	MARLENE
GABRIEL QUISPE JORGE	920106612	30-Mar	GERARDO
ARIAS PAREDES CARMEN ROSA MARIA	952398191	2-Set	CONSUELO
ROUSS CALLE	970449095	26-May	JACQUELIN LUCANO
	997768261	26-Set	GABRIEL/MANUEL
HERRERA ENRIQUEZ DENNIS AMERICO	996708070	9-Set	MANUEL VOLCANES
SALAZAR ROMAN MARISOL	955249448	16-Ene	OLGA CHEPE
LIVIA PAUCCA CARLO VALENTINO	947181945	26-Ene	GABRIEL DEL PINO
GARCIA GAMARRA PABEL	952176454	23-Jun	GABRIEL DEL PINO
MADUEÑO EVANGELISTA LUCIA ERACLEA	995686402	26-May	FLOR/MANUEL
JULIO ZARATE	943554289	4-Oct	MANUEL VOLCANES
QUISPE ALARTE MARLENE	992985969	10-Abr	GABRIEL DEL PINO

YULIANA MARQUEZ	922457863		FLOR / LILIANA
ZULEMA SILVA 	956789651		FLOR / LILIANA
	926912074	10-Mar	
	991298930	16-Ene	
BAZAN MALLMA ANNIE JOSELINE	970348305	3-Ene	MARLENE
CASSANO BARBOZA EVA GRACIELA	957307832	14-Mar	CONSUELO
RETUERTO ALBURQUEQUE JUAN FRANCISCO	992261223	11-Jun	
MARIRUZ RIVERA RAMIREZ	993490213		CORRECCION PATRICIA TORRES
MERY CARBAJAL	904411608	27-Mar	JACQUELIN / MARLENE
SUAREZ CARBAJAL JULIO CESAR	969173225	7-Feb	
PEÑA CORONADO MARILYN ELIZABETH	982959485	14-Ene	OLGA
LEVANO BALDEON ROSMERY NATALY	965451759	30-Mar	CONSUELO
HUAMANYAURI CUELLAR VIANNEY MARGARITA	987078705	16-May	PATY/CONSUELO/JACQUI
VALDIVIA ARELLANO ALEXIS GOHAN	907328737	31-Dic	MANUEL VOLCANES
RIVEROS MARTINEZ CLAUDIA INES	943586175	13-Dic	
SERNA SANTOS WILDER CESAR	951689745	17-Dic	
MEZA HORNA ENMANUEL ALONSO	960103869	25-Mar	JULIHNO MENDOZA 
VARGAS ALEGRIA LORENA MARIA EMILIA	980757358	7-Nov	consuelo
RICALDI FERNANDEZ GISELLA	991902735	29-Jul	OLGA
VARGAS ALEGRIA GRECIA KATHERINE	914984446	21-Set	JACQUELIN
MUNDO LEVANO CARLA KATTERINE	992851066	12-Mar	JACQUELIN
HUAREZ SALAZAR JHERSON CARLOS	955024070	12-Abr	MANUEL VOLCANES
MILUSKA SEGURA LEVANO	952237964	21-Set	FLOR
CHAVEZ MENDEZ RONALD ALEXIS	981217283	2-Mar	JULIHNO MENDOZA 
PANDURO CASTRO GERARDO	923753014	6-Set	DANDY
ROJAS ROMERO JESUS GABRIELA	989527027	16-Jun	OLGA
HANNA GARCIA VILCHES	958235888	18-Set	PATY  
FERNANDEZ CONTRERAS DERMALY	966222668	29-Oct	
SALAZAR CASTILLO OSCAR ADRIAN	929479662	11-Dic	JULIHNO MENDOZA 
ESPINOZA CHINCHAY JENNIFER FIORELLA	946152052	22-Jul	
MOSTACERO SOSA VALERY JAVIER	940407008	3-Dic	MANUEL VOLCANES
HUARINGA CHAGRAY JHOAN ALEXANDER	999957722	15-Mar	DANDY
ARIAS CABRERA SHIRLEY SARA	994195760	5-Ene	FLOR
CARDENAS MOSCOSO ELENA NONA NATIVIDAD	960209601	5-Ago	CONSUELO
	923129429	24-Jul	JULIHNO MENDOZA 
JESICA CHAGRAY CUELLAR	966751821	11-Jul	
CACERES REYES ANA LUCIA	946886176	13-Abr	OLGA
CALLUPE LLAJA WILLIAM ARTURO	963932581	5-Set	JULIHNO/DANDY
MAMANI ARRIOLA GLADYS VANESSA DEL PILAR	932705636	22-Jun	PATY
MARISOL PAUCAR FLORES 	943780503	17-Dic	FLOR
RIVERA CORNEJO RICARDO ANDRE	992970204	3-May	MARLENE / JULIHNO
VELIZ FRANCIA GISEL NOEMI	957333000	17-Ene	JACQUELIN
VENTOCILLA TALAVERANO REY DAVID	924607859	28-May	DANDY
ANDREA CASTAÑEDA MARCA	966455323		
ANTONIO PIMENTEL CLAUDIA MARIA	999953181		
ARANGO PEREZ HELEN YESENIA	952306535		
AREVALO TERRONES FLOR DE MARIA	975511324		
BACA CABRAL ROCIO	943181722		
BARNUEVO JUAREZ ALEXANDRA DANIELA	982281106		
BAZAN MALLMA MARITZA FIORELLA	947759117		
BELTRAN COLAN PATRICIA CECILIA	982862301		
BLAS ROJAS JHEINER YURI	991750255		
CAMIZAN SANGAMA RENATO	951416302		
CAMIZAN SANGAMA RICARDO	937337503		
CONDORI CHIPANA MARCO ANTONI	934575282	15-Nov	
PALACIOS SANCHEZ MANUEL OCTAVIO	997768261	26-Set	MANUEL VOLCANES






















